id: IBBB36F26
legacy_id: P010475
ocr_import_info:
  bdrc_scan_id: W00KG09211
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T04:27:12'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:27:51.717724+00:00'
last_modified: 2022-08-29 20:29:37.778380
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG09211
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00KG09211
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དག་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ཀཱིརྟི་བཛྲ།
statistics:
  ocr_word_mean_confidence_index: 0.6143391672251506
  ocr_word_median_confidence_index: 0.6299999952316284
quality: null
bases:
  I00KG09360:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG09360
      total_pages: 1138
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00KG09360.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.6078123148371664
    legacy_id: v002
  I00KG09359:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG09359
      total_pages: 870
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG09359.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6201498079425759
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
