id: P010475
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG09211
  title: དག་ཡིག་ཕྱོགས་བསྒྲིགས་
  author: ''
  volumes:
    9c10b840785d4d4197b614eda8f0a418:
      image_group_id: I00KG09359
      title: ''
      volume_number: 1
      total_pages: 870
    ac4a148d0a6442faaf58693815813faa:
      image_group_id: I00KG09360
      title: ''
      volume_number: 2
      total_pages: 1138
